#pragma once
#include <iostream>
#include <unordered_map>
#include <string>

#include <sys/socket.h>
#include <sys/types.h>
#include <sys/epoll.h>
#include <unistd.h>
#include <netdb.h>

#include <arpa/inet.h>

#define RECV_BUFFER_SIZE 100
#define SEND_BUFFER_SIZE 100

// EPOLL_BUFFER_SIZE must be 1 for EPOLLET
#define PROCESS_EPOLL_BUFFER_SIZE 1
#define MASTER_EPOLL_BUFFER_SIZE 1
#define WORKER_EPOLL_BUFFER_SIZE 1
#define PROCESS_EPOLL_MODE EPOLLIN|EPOLLRDHUP|EPOLLET|EPOLLWAKEUP
#define MASTER_EPOLL_MODE EPOLLIN|EPOLLET|EPOLLWAKEUP
#define WORKER_EPOLL_MODE EPOLLIN|EPOLLRDHUP|EPOLLET|EPOLLWAKEUP
#define PROCESS_EPOLL_TIMEOUT 20000
#define MASTER_EPOLL_TIMEOUT 20000
#define WORKER_EPOLL_TIMEOUT 20000
#define QUEUE_SIZE 1024

#define RECV_FLAGS MSG_DONTWAIT|MSG_NOSIGNAL
#define SEND_FLAGS MSG_DONTWAIT|MSG_NOSIGNAL

#define MAX_NUM_OF_CONNECTION 256
#define NUM_OF_WORKERS 0
